version: '3.7'
services:
  # Start the OpenSearch DB
  opensearch:
    image: opensearchproject/opensearch:1.2.4
    #image: opensearchproject/opensearch:latest
    environment:
      discovery.type: single-node  # Run on a single node
      plugins.security.disabled: "true" # disable https and logins - only for DEV
      compatibility.override_main_response_version: "true"  # override the version conflict that can occur between Kafka and our Container for OpenSearchs
    ports:
      - 9200:9200  # OpenSearch DB url : localhost:9200
      - 9600:9600 # required for Performance Analyzer


  # Start the Console to access the OpenSearch DB
  # url: http://localhost:5601/
  # console at http://localhost:5601/app/dev_tools#/console
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:1.2.0
    #image: opensearchproject/opensearch-dashboards:latest
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
